AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECR repo for todo

Parameters:
  RepositoryName:
    Type: String
    Default: todo-app

Resources:

  TodoAppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt TodoAppRepository.RepositoryUri
  RepositoryName:
    Value: !Ref TodoAppRepository
