apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: default
type: Opaque
stringData:
  MONGODB_URI: "mongodb://appuser:<REPLACE-AT-DEPLOY-TIME>@<MONGO-PRIVATE-IP>:27017/go-mongodb"
  SECRET_KEY: "<REPLACE-AT-DEPLOY-TIME-random-string-for-JWT-signing>"
